spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AlertService
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092